AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 Instance Deployment with SSH Security Group

Parameters:
  SubnetId:
    Type: String
    Description: Subnet for the EC2 instance
    Default: subnet-0e699773a388d27ad
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
    Description: EC2 instance type
  AMIid:
    Type: AWS::EC2::Image::Id
    Default: ami-0c02fb55956c7d316  # Amazon Linux 2 in us-east-1
    Description: AMI ID for EC2

Resources:
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH access
      VpcId: vpc-087a31168107445a5   # Replace with your actual VPCId from the outputs above
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 0
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: ec2-ssh-sg

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref AMIid
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
      Tags:
        - Key: Name
          Value: assignment3-ec2

Outputs:
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref MyEC2Instance
  InstancePublicIp:
    Description: Public IP Address of the EC2 instance
    Value: !GetAtt MyEC2Instance.PublicIp
